export const projects = [
  {
    title: 'Portfolio Website',
    description: "This was my personal portfolio website that has all my work and project experience, including my resume. It used to be my main portfolio before deploying this current portfolio.",
    image: '/images/portfolio.jpg',
    tags: ['Nextjs', 'Emailjs', 'Tawk.to Chat', 'Bootstrap'],
    source: 'https://github.com/smey-cam/portfolio-kh',
    visit: 'https://chhamdararaksmey.vercel.app/',
    id: 1,
  },
  {
    title: 'Tour Cam Website',
    description: "Cambodia specialising in tailor-made, private guided tours to Siem Reap, Phnom Penh, Sihanoukville, Kampot and Kep.",
    image: '/images/tourweb.png',
    tags: ['HTML', 'CSS', 'Javascript', 'Bootstrap'],
    source: 'https://github.com/smey-cam/web-tours-cam',
    visit: 'https://web-tours-cam.vercel.app/',
    id: 2,
  },
  {
    title: 'Personal Finance Management System',
    description: "Personal financial management (PFM) refers to the process of managing one's finances effectively to achieve financial goals and objectives.",
    image: '/images/eb.jpg',
    tags: ['MERN stack','Tailwind', 'MongoDB'],
    source: 'https://github.com/chhamdararaksmeydeveloper168-del/personal-income-expense',
    visit: 'https://personal-income-expense.onrender.com',
    id: 3,
  },
  {
    title: 'School Management System',
    description: "A School Management System (SMS) is an integrated platform designed to streamline and automate the various administrative and academic operations of a school. It enables efficient management of school resources, improves communication among stakeholders, and enhances the overall educational experience for students.",
    image: '/images/abs.png',
    tags: ['Reactjs', 'Bootstrap'],
    source: 'https://github.com/school-management-system-org-kh/edu-backend',
    visit: 'https://edu-backend-393j.onrender.com',
    id: 4,
  },
  {
    title: 'Trello Cambodia',
    description: "Trello-Cam is a modern, collaborative project management web application combining the intuitive visual layout of Trello's Kanban boards with the powerful Sprint planning and Scrum functionalities of Jira. It features real-time synchronization, interactive charts, and multi-language support (English, Khmer, Chinese).",
    image: '/images/todo.png',
    tags: ['React', 'Node', 'Antd Design', 'MongoDB'],
    source: 'https://trello-cam-frontend.onrender.com/',
    visit: 'https://trello-cam-frontend.onrender.com/',
    id: 5,
  },
  {
    title: 'Web Site Ecommerce',
    description: "A modern eCommerce platform offering a seamless shopping experience with a wide range of products, secure payments, and fast delivery.",
    image: '/images/sreymoeunsoeungkhmer.png',
    tags: ['ReactJs', 'Antd Design', 'Bootstrap'],
    source: 'https://github.com/raksmeyaeu/soeungkhmer',
    visit: 'https://sreymoeunsoeungkhmer.netlify.app/',
    id: 6,
  },
  {
    title: 'University Management System',
    description: "A University Management System is a digital platform designed to manage and automate the daily operations of a university or higher education institution. It helps administrators, lecturers, students, and staff efficiently handle academic and administrative tasks through a centralized system.",
    image: '/images/university.png',
    tags: ['ReactJs', 'NodeJs', 'MongoDB'],
    source: 'https://github.com/university-system-org-kh/university-system',
    visit: 'https://university-management-system-yfz1.onrender.com/',
    id: 7,
  },
  {
    title: 'Khmer-English Traffic Sign OCR',
    description: "A full-stack, AI-powered system that reads arbitrary road traffic signs, converts numbers or words via instant OCR, and translates warning instructions securely to both English and Khmer, complete with audio support and flashcard test practices.",
    image: '/images/traffic-sign-ocr.png',
    tags: ['Python', 'OpenCV', 'TensorFlow', 'React', "Node", "Gemini"],
    source: 'https://github.com/traffic-sign-ocr-org-kh/traffic-sign-ocr',
    visit: 'https://khmer-english-traffic-sign-ocr.onrender.com/',
    id: 8,
  },
];