export const projects = [
  {
    title: 'Personal Finance',
    description: "Personal financial management (PFM) refers to the process of managing one's finances effectively to achieve financial goals and objectives.",
    image: '/images/covid.jpg',
    tags: ['Android', 'XML', 'Firebase', 'Rest API'],
    source: 'https://github.com/Personal-Income/Androidv1',
    visit: '',
    id: 0,
  },
  {
    title: 'Portfolio Website',
    description: "This was my personal portfolio website that has all my work and project experience, including my resume. It used to be my main portfolio before deploying this current portfolio.",
    image: '/images/portfolio.jpg',
    tags: ['Nextjs', 'Emailjs', 'Tawk.to Chat', 'Bootstrap'],
    source: 'https://github.com/smey-cam/portfolio-kh',
    visit: '',
    id: 1,
  },
  {
    title: 'Tour Cam Website',
    description: "Cambodia specialising in tailor-made, private guided tours to Siem Reap, Phnom Penh, Sihanoukville, Kampot and Kep.",
    image: '/images/tourweb.png',
    tags: ['HTML', 'CSS', 'Javascript', 'Bootstrap'],
    source: 'https://github.com/smey-cam/web-tours-cam',
    visit: 'https://web-tours-cam.vercel.app/',
    id: 2,
  },
  {
    title: 'Personal Finance Management System',
    description: "Personal financial management (PFM) refers to the process of managing one's finances effectively to achieve financial goals and objectives.",
    image: '/images/eb.jpg',
    tags: ['Nextjs', 'Javascript', 'Material UI'],
    source: 'https://github.com/chhamdararaksmeydeveloper168-del/personal-income-expense',
    visit: 'https://personal-income-expense.onrender.com',
    id: 3,
  },
  {
    title: 'School Management System',
    description: "A School Management System (SMS) is an integrated platform designed to streamline and automate the various administrative and academic operations of a school. It enables efficient management of school resources, improves communication among stakeholders, and enhances the overall educational experience for students.",
    image: '/images/abs.png',
    tags: ['Reactjs', 'Bootstrap'],
    // source: 'https://github.com/smey-cam/presonal-income-expense',
    // visit: '',
    id: 4,
  },
  {
    title: 'Personal Finance[API]',
    description: "Personal financial management (PFM) refers to the process of managing one's finances effectively to achieve financial goals and objectives.",
    image: '/images/apiPersonalFinance.jpg',
    tags: ['NodeJs', 'ExpressJs', 'MongoDB'],
    source: 'https://github.com/smey-cam/financial-management-api',
    visit: '',
    id: 5,
  },
  {
    title: 'To-Do List',
    description: "Personal financial management (PFM) refers to the process of managing one's finances effectively to achieve financial goals and objectives.",
    image: '/images/todo.png',
    tags: ['Python', 'mySQL', 'Bootstrap'],
    source: 'https://github.com/smey-cam/AI/tree/main/pythonvenv',
    visit: '',
    id: 6,
  },
  {
    title: 'Web Site Ecommerce',
    description: "A modern eCommerce platform offering a seamless shopping experience with a wide range of products, secure payments, and fast delivery.",
    image: '/images/sreymoeunsoeungkhmer.png',
    tags: ['ReactJs', 'Antd Design', 'Bootstrap'],
    source: 'https://github.com/raksmeyaeu/soeungkhmer',
    visit: 'https://sreymoeunsoeungkhmer.netlify.app/',
    id: 7,
  },
  {
    title: 'Movie Streaming Platform',
    description: "Movie Stream Web App is an online platform that allows users to browse, search, and stream movies instantly. It provides a smooth user interface, fast loading performance, and organized categories to enhance the entertainment experience across desktop and mobile devices.",
    image: '/images/movie.jpg',
    tags: ['ReactJs', 'Tailwindcss', 'TypeScript'],
    source: 'https://github.com/movie-stream-org-kh/movie-stream-web-app',
    visit: 'https://movie-stream-web-app.onrender.com/',
    id: 8,
  },
];